service: iotauth

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    ROLE_NAME: iotauthRole-${self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'iot:DescribeEndpoint'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: "*"

functions:
  auth:
    handler: handler.auth
    events:
      - http: GET iot/keys


resources:
  Resources:
    iotEventRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName:
          Fn::Join: [ '-', ['iotauthRole',  '${self:provider.stage}' ]]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::Join: [ '', ['arn:aws:iam::', Ref: 'AWS::AccountId', ':root']]
            Action:
            - sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: iotconnect
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iot:Connect
              Resource: '*'
        - PolicyName: iotsub
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iot:Subscribe
              Resource:
                - 'Fn::Join':
                  - ''
                  -
                    - 'arn:aws:iot:'
                    - Ref: "AWS::Region"
                    - ':'
                    - Ref: "AWS::AccountId"
                    - ":topicfilter/processa-"
                    - ${self:provider.stage}
                    - '/*'
        - PolicyName: iotsrecv
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iot:Receive
              Resource:
                - 'Fn::Join':
                  - ''
                  -
                    - 'arn:aws:iot:'
                    - Ref: "AWS::Region"
                    - ':'
                    - Ref: "AWS::AccountId"
                    - ":topic/processa-"
                    - ${self:provider.stage}
                    - '/*'

